rules:
  bugs:
    argument-always-wildcard:
      ignore:
        files:
          - library/utils
    constant-condition:
      level: error
      ignore:
        files:
          - library/utils/
          - e2e/cli/
  idiomatic:
    directory-package-mismatch:
      level: ignore
    no-defined-entrypoint:
      level: ignore
  imports:
    implicit-future-keywords:
      level: ignore
    unresolved-reference:
      level: ignore
  style:
    external-reference:
      ignore:
        files:
          - library/utils
    rule-name-repeats-package:
      ignore:
        files:
          - e2e/data/kafka/testdata/bundles/
          - test/cli/smoke/
    opa-fmt:
      level: ignore
    todo-comment:
      level: ignore
  testing:
    metasyntactic-variable:
      level: error
      ignore:
        files:
          - "*test.rego"
    test-outside-test-package:
      level: error
      ignore:
        files:
          - e2e/
          - test/cli/

ignore:
  files:
    - pkg/rego_vm/testdata/monster.rego
