version: 2
updates:
  - package-ecosystem: gomod
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: daily
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2/*"
          - "github.com/aws/aws-sdk-go-v2"
          - "github.com/aws/aws-sdk-go"
      go.opentelemetry.io:
        patterns:
          - "go.opentelemetry.io/*"
      vault:
        patterns:
          - "github.com/hashicorp/vault/*"
      testcontainers:
        patterns:
          - "github.com/testcontainers/*"
      franz-go:
        patterns:
          - "github.com/twmb/*"
  - package-ecosystem: gomod
    open-pull-requests-limit: 10
    directory: /e2e
    schedule:
      interval: daily
    groups:
      go.opentelemetry.io:
        patterns:
          - "go.opentelemetry.io/*"
      vault:
        patterns:
          - "github.com/hashicorp/vault/*"
      testcontainers:
        patterns:
          - "github.com/testcontainers/*"
      franz-go:
        patterns:
          - "github.com/twmb/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
