version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  groups: &go-groups
    go.opentelemetry.io:
      patterns:
      - "go.opentelemetry.io/*"
    vault:
      patterns:
      - "github.com/hashicorp/vault/*"
    testcontainers:
      patterns:
      - "github.com/testcontainers/*"
- package-ecosystem: gomod
  directory: /e2e
  schedule:
    interval: daily
  groups: *go-groups
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
