run:
  timeout: 5m
  build-tags:
    - use_opa_fork
linters-settings:
  lll:
    line-length: 200

  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        severity: warning
        disabled: false
        arguments:
          - allowRegex: "^_"

output:
  print-issued-lines: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - revive # replacement for golint
    - gofmt
    - goimports
    - unused
    - typecheck
    - staticcheck
    - gosimple
    - prealloc

issues:
  exclude:
    - "var-naming: don't use an underscore in package name"
    - "var-naming: var (.*Json.*) should be "
    - "var-naming: type (.*Json.*) should be "
    - "unexported-return: exported method (.*) returns unexported type"
    - "exported: type name will be used (.*) by other packages, and that stutters"
  exclude-dirs:
    - pkg/json/internal # copied from stdlib
