run:
  timeout: 5m

linter-settings:
  lll:
    line-length: 200

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - revive # replacement for golint
    - gofmt
    - goimports
    - unused
    - misspell
    - typecheck
    - staticcheck
    - gosimple
    - prealloc
    # - gosec # too many false positives

issues:
  exclude:
    - "var-naming: don't use an underscore in package name"
    - "var-naming: var (.*Json.*) should be "
    - "var-naming: type (.*Json.*) should be "
    - "unexported-return: exported method (.*) returns unexported type"
    - "exported: type name will be used (.*) by other packages, and that stutters"
