run:
  timeout: 5m

linter-settings:
  lll:
    line-length: 200

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - revive # replacement for golint
    - gofmt
    - goimports
    - unused
    - varcheck
    - deadcode
    - misspell
    - typecheck
    - structcheck
    - staticcheck
    - gosimple
    # - gosec # too many false positives

issues:
  exclude:
    - "var-naming:"
    - "unexported-return:"
    - "exported: type name"
