version: "2"
run:
  build-tags:
    - use_opa_fork
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - prealloc
    - revive
    - staticcheck
    - unused
  settings:
    lll:
      line-length: 200
    revive:
      rules:
        - name: unused-parameter
          arguments:
            - allowRegex: ^_
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'var-naming: don''t use an underscore in package name'
      - path: (.+)\.go$
        text: 'var-naming: var (.*Json.*) should be '
      - path: (.+)\.go$
        text: 'var-naming: type (.*Json.*) should be '
      - path: (.+)\.go$
        text: 'unexported-return: exported method (.*) returns unexported type'
      - path: (.+)\.go$
        text: 'exported: type name will be used (.*) by other packages, and that stutters'
    paths:
      - pkg/json/internal
      - internal/benthos
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - pkg/json/internal
      - internal/benthos
      - third_party$
      - builtin$
      - examples$
