project_name: eopa
version: 2

env:
  - CGO_ENABLED=0

builds:
  - id: linux-build
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
    ldflags: &ldflags
      - -s
      - -X github.com/open-policy-agent/eopa/internal/version.Version={{.Env.EOPA_VERSION}}
      - -X github.com/open-policy-agent/eopa/internal/version.Hostname=github.actions.local
      - -X github.com/open-policy-agent/opa/internal/report.GHRepo={{.Env.EOPA_GH_REPO}}
  - id: darwin-build
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
    ldflags: *ldflags
  - id: windows-build
    goos:
      - windows
    goarch:
      - amd64
    tags:
    ldflags: *ldflags
    hooks:
      pre:
        # Embeds metadata and an icon into the executable at build-time.
        - cmd: build/gen-windows-versioninfo.sh

archives:
  - id: binary
    formats: binary
    files:
      - none*
    # example: eopa_Darwin_arm64
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "checksums.txt"

changelog:

release:
  github:
    owner: open-policy-agent
    name: eopa
