project_name: load
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
      - -X github.com/open-policy-agent/opa/version.Program=Load
      - -X github.com/open-policy-agent/opa/version.Version={{.Env.LOAD_VERSION}}
      - -X github.com/open-policy-agent/opa/internal/report.ExternalServiceURL=https://telemetry.openpolicyagent.org
      - -X github.com/open-policy-agent/opa/version.Hostname={{.Env.HOSTNAME}}

archives:
  - id: binary
    format: binary
    files:
      - none*
    # example: load_Darwin_arm64
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:

release:
  github:
    owner: StyraInc
    name: load

brews:
  - tap:
      owner: styrainc
      name: homebrew-packages
    url_template: >-
      https://github.com/StyraInc/load/releases/download/{{ .Tag }}/{{ .ProjectName }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    commit_author:
      name: Styra DevRel
      email: devrel@styra.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://www.styra.com/styra-load"
    description: "Styra Load is an enterprise-grade authorization engine built to provide resource-efficient performance for data-heavy workloads"
