project_name: eopa

env:
  - CGO_ENABLED=0

builds:
  - id: linux-windows-build
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    tags:
      - use_opa_fork
    ldflags: &ldflags
      - -s
      - -X github.com/styrainc/enterprise-opa-private/internal/version.Version={{.Env.EOPA_VERSION}}
      - -X github.com/styrainc/enterprise-opa-private/internal/version.Hostname=github.actions.local
      - -X github.com/open-policy-agent/opa/internal/report.ExternalServiceURL={{.Env.EOPA_TELEMETRY_URL}}
  - id: darwin-build
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - use_opa_fork
    ldflags: *ldflags
    hooks:
      post:
        # The binary is signed and notarized when running a production release,
        # but for snapshot builds notarization is skipped and only ad-hoc
        # signing is performed (not cryptographic material is needed).
        #
        # note: environment variables required for signing
        #   QUILL_SIGN_P12, QUILL_SIGN_PASSWORD
        # Don't sign snapshots, signing is beneficial if you do
        # download the snapshot/pr build from the GHA artifact,
        # but it also adds extra time to each build.
        - cmd: quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
          env:
            - QUILL_LOG_FILE=/tmp/quill-{{ .Target }}.log

archives:
  - id: binary
    format: binary
    files:
      - none*
    # example: eopa_Darwin_arm64
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:

release:
  github:
    owner: StyraInc
    name: enterprise-opa

brews:
  - repository:
      owner: StyraInc
      name: homebrew-packages
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    url_template: >-
      https://github.com/StyraInc/enterprise-opa/releases/download/{{ .Tag }}/{{ .ProjectName }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    commit_author:
      name: Styra DevRel
      email: devrel@styra.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://www.styra.com/enterprise-opa"
    description: "Styra Enterprise OPA is an enterprise-grade authorization engine built to provide resource-efficient performance for data-heavy workloads"
