builds:
- id: main
  env:
  - GOPRIVATE=github.com/StyraInc/opa
  flags:
  - -buildmode=exe
  ldflags:
  # TODO: fix the load-telemetry URL once we have that changed...
  - -X github.com/open-policy-agent/opa/internal/report.ExternalServiceURL=https://load-telemetry.corp.styra.com
  - -X github.com/open-policy-agent/opa/version.Hostname=github.actions.local
  - -X "github.com/open-policy-agent/opa/version.Program=Enterprise OPA"
  - -X github.com/open-policy-agent/opa/version.Version={{.Env.EOPA_VERSION}}
  - -X "github.com/open-policy-agent/opa/version.AltProgram=Open Policy Agent"
  - -X github.com/open-policy-agent/opa/version.AltVersion={{.Env.OPA_VERSION}}
