builds:
  - id: main
    flags:
      - -buildmode=exe
    ldflags:
      - -X github.com/open-policy-agent/eopa/internal/version.Version={{.Env.EOPA_VERSION}}
      - -X github.com/open-policy-agent/eopa/internal/version.Hostname=github.actions.local
      - -X github.com/open-policy-agent/opa/internal/report.GHRepo={{.Env.EOPA_GH_REPO}}
