# Copyright 2025 The OPA Authors
# SPDX-License-Identifier: Apache-2.0

# Note(philip): Only used in CI to enable the .go-version file for mise.

[settings]
idiomatic_version_file_enable_tools = ["go"]
