disco.tar.gz:
	eopa build -o disco.tar.gz disco

disco.bjson.tar.gz: disco.tar.gz
	eopa bundle convert disco.tar.gz disco.bjson.tar.gz

disco-license.tar.gz:
	eopa build -o disco-license.tar.gz disco-license

disco-license.bjson.tar.gz: disco-license.tar.gz
	eopa bundle convert disco-license.tar.gz disco-license.bjson.tar.gz
