name: Check

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOPRIVATE: github.com/StyraInc/opa

jobs:
  lint:
    name: Analysis & Linting
    runs-on: ubuntu-22.04
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - name: Setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      # NOTE(sr): we need to install this before checking out the code, as it will otherwise
      # interfere with the project's go.mod/go.sum
      - name: install gcassert
        run: go install github.com/jordanlewis/gcassert/cmd/gcassert@latest
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          skip-pkg-cache: true
          skip-build-cache: true
      - name: gcassert
        run: gcassert ./...

  test:
    name: Test
    runs-on: ubuntu-22.04
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - uses: open-policy-agent/setup-opa@v2
      - name: checkout Load
        uses: actions/checkout@v3
        with:
          path: load
      - name: pick up opa version
        id: load
        run: echo "opa_version=v$(build/get-opa-version.sh)" >> $GITHUB_OUTPUT
        working-directory: load
      - name: checkout OPA
        uses: actions/checkout@v3
        with:
          repository: open-policy-agent/opa
          ref: ${{ steps.load.outputs.opa_version }}
          path: opa
      - name: pick up opa directory
        id: opa
        working-directory: opa
        run: echo "dir=$(pwd)" >> $GITHUB_OUTPUT
      - name: setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - run: make test
        working-directory: load
        env:
          OPA_ROOT: ${{ steps.opa.outputs.dir }}
      - name: gobenchdata check
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        env:
          INPUT_GO_TEST_FLAGS: -timeout=10m
          INPUT_SUBDIRECTORY: load
          INPUT_CHECKS: true
          INPUT_CHECKS_CONFIG: load/gobenchdata-checks.yml
          INPUT_PUBLISH_BRANCH: benchmarks
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
        timeout-minutes: 10
        if: github.ref != 'refs/heads/main' # do not run for commits on main

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-22.04
    needs: build
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - uses: open-policy-agent/setup-opa@v2
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - name: Download image tarball
        uses: actions/download-artifact@v3
        with:
          name: image
      - name: Load image
        id: load
        run: |
          echo "image=$(docker load --quiet --input local.tar | awk '{print $3}')" >> $GITHUB_OUTPUT
          echo "bundles=$(pwd)/e2e" >> $GITHUB_OUTPUT
      - name: checkout opa-testing-e2e
        uses: actions/checkout@v3
        with:
          repository: StyraInc/opa-testing-e2e
          path: _e2e
          token: ${{ secrets.GH_API_TOKEN }}
          persist-credentials: false
      - run: make test
        working-directory: _e2e
        env:
          IMAGE: ${{ steps.load.outputs.image }}
          BUNDLES: ${{ steps.load.outputs.bundles }}
          BUNDLE_FILE_PATH: bundles/systems/bc01d50d17d7446684c4e6c34a1ad07f
          NUM_INPUT_BUNDLES: 2
          BUNDLE_HOST: 172.17.0.1

  build:
    name: Ko Build
    runs-on: ubuntu-22.04
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - uses: open-policy-agent/setup-opa@v2
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - uses: imjasonh/setup-ko@v0.6
      - name: Build
        run: make build
      - name: Upload image tarball
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: local.tar

  smoke-cli:
    name: Smoke Test CLI
    runs-on: ubuntu-22.04
    needs: build
    environment: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download image tarball
        uses: actions/download-artifact@v3
        with:
          name: image
      - name: Load image
        id: load
        run: echo "image=$(docker load --quiet --input local.tar | awk '{print $3}')" >> $GITHUB_OUTPUT
      - run: make test
        working-directory: e2e/cli
        env:
          IMAGE: ${{ steps.load.outputs.image }}

  deploy:
    name: Push Latest Release
    if: github.ref == 'refs/heads/main' # only true for pushes to `main`
    runs-on: ubuntu-22.04
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - uses: open-policy-agent/setup-opa@v2
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: 547414210802.dkr.ecr.us-east-1.amazonaws.com/styra
      - name: Build and Push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Only run if required secrets are provided
        if: ${{ env.AWS_ACCESS_KEY_ID && env.AWS_SECRET_ACCESS_KEY }}
        run: make deploy-ci
