name: Check

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # All jobs essentially re-create the `ci-release-test` make target, but are split
  # up for parallel runners for faster PR feedback and a nicer UX.
  build:
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v2
      - uses: imjasonh/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: dont-publish-yet
      - uses: actions/checkout@v3
      - name: setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - run: make build
