name: Check

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOPRIVATE: github.com/StyraInc/opa

jobs:
  lint:
    name: Analysis & Linting
    runs-on: ubuntu-22.04
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - name: Setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      # NOTE(sr): we need to install this from a different workdir, as it will otherwise
      # interfere with the project's go.mod/go.sum
      - name: install gcassert
        run: go install github.com/jordanlewis/gcassert/cmd/gcassert@latest
        working-directory: /tmp
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.0
          skip-pkg-cache: true
          skip-build-cache: true
      - name: gcassert
        run: gcassert ./...

  test:
    name: Test
    runs-on: ubuntu-22.04
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - uses: open-policy-agent/setup-opa@v2
      - name: checkout Load
        uses: actions/checkout@v3
        with:
          path: load
      - uses: actions/setup-go@v3
        with:
          go-version-file: load/go.mod
          cache-dependency-path: load/go.sum
          check-latest: true
          cache: true
      - name: pick up opa version
        id: load
        run: echo "opa_version=v$(build/get-opa-version.sh)" >> $GITHUB_OUTPUT
        working-directory: load
      - name: checkout OPA
        uses: actions/checkout@v3
        with:
          repository: open-policy-agent/opa
          ref: ${{ steps.load.outputs.opa_version }}
          path: opa
      - name: pick up opa directory
        id: opa
        working-directory: opa
        run: echo "dir=$(pwd)" >> $GITHUB_OUTPUT
      - name: setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - run: make test
        working-directory: load
        env:
          OPA_ROOT: ${{ steps.opa.outputs.dir }}
      - run: make benchmark
        working-directory: load
      - name: gobenchdata check
        run: go run go.bobheadxi.dev/gobenchdata@v1 action
        env:
          INPUT_GO_TEST_FLAGS: -timeout=10m
          INPUT_SUBDIRECTORY: load
          INPUT_CHECKS: true
          INPUT_CHECKS_CONFIG: load/gobenchdata-checks.yml
          INPUT_PUBLISH_BRANCH: benchmarks
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
        timeout-minutes: 10
        if: github.ref != 'refs/heads/main' # do not run for commits on main

  test-e2e:
    name: Test E2E
    runs-on: ubuntu-22.04
    needs: build
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - uses: open-policy-agent/setup-opa@v2
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - name: Download image tarball
        uses: actions/download-artifact@v3
        with:
          name: image
      - name: Load image
        id: load
        run: |
          echo "image=$(docker load --quiet --input local.tar | awk '{print $3}')" >> $GITHUB_OUTPUT
          echo "bundles=$(pwd)/e2e" >> $GITHUB_OUTPUT
      - run: make e2e
        env:
          IMAGE: ${{ steps.load.outputs.image }}
          STYRA_LOAD_LICENSE_TOKEN: ${{ secrets.STYRA_LOAD_LICENSE_TOKEN }}
      - name: checkout opa-testing-e2e
        uses: actions/checkout@v3
        with:
          repository: StyraInc/opa-testing-e2e
          path: _e2e
          token: ${{ secrets.GH_API_TOKEN }}
          persist-credentials: false
      - name: run "opa-testing-e2e"
        run: make test
        working-directory: _e2e
        env:
          STYRA_LOAD_LICENSE_TOKEN: ${{ secrets.STYRA_LOAD_LICENSE_TOKEN }}
          IMAGE: ${{ steps.load.outputs.image }}
          BUNDLES: ${{ steps.load.outputs.bundles }}
          BUNDLE_FILE_PATH: bundles/systems/bc01d50d17d7446684c4e6c34a1ad07f
          NUM_INPUT_BUNDLES: 2
          BUNDLE_HOST: 172.17.0.1

  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-22.04
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - uses: open-policy-agent/setup-opa@v2
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
      - name: Make GoReleaser
        run: make release
        env:
          HOSTNAME: github.actions.local
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            dist/checksums.txt
            dist/*gz
            dist/*zip

  build:
    name: Ko Build
    runs-on: ubuntu-22.04
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    steps:
      - uses: open-policy-agent/setup-opa@v2
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true
      - name: Setup github api token
        run: git config --global url.https://$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - uses: ko-build/setup-ko@v0.6
      - name: Build
        run: make build
      - name: Upload image tarball
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: local.tar

  smoke-cli:
    name: Smoke Test CLI
    runs-on: ubuntu-22.04
    needs: build
    environment: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Download image tarball
        uses: actions/download-artifact@v3
        with:
          name: image
      - name: Load image
        id: load
        run: echo "image=$(docker load --quiet --input local.tar | awk '{print $3}')" >> $GITHUB_OUTPUT
      - run: make test
        working-directory: e2e/cli
        env:
          STYRA_LOAD_LICENSE_TOKEN: ${{ secrets.STYRA_LOAD_LICENSE_TOKEN }}
          IMAGE: ${{ steps.load.outputs.image }}

  smoke-test-releases:
    name: Smoke Test Releases
    runs-on: ${{ matrix.os }}
    needs: goreleaser
    environment: ci
    env:
      GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            archive: dist/load_Linux_x86_64.tar.gz
            exec: load
          - os: macos-latest
            archive: dist/load_Darwin_x86_64.tar.gz
            exec: load
          - os: windows-latest
            archive: dist/load_Windows_x86_64.zip
            exec: load.exe

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Download release binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: dist
      - name: Test binaries
        run: make ci-smoke-test ARCHIVE=${{ matrix.archive }} BINARY=${{ matrix.exec }}
        env:
          STYRA_LOAD_LICENSE_TOKEN: ${{ secrets.STYRA_LOAD_LICENSE_TOKEN }}
