# this workflow is used to update the EOPA CLI docs content at
# docs.styra.com when it changes in this repo on release.
name: Update Docs

on:
  push:
    tags:
      - v[0-9].**
  workflow_dispatch:

env:
  GOPRIVATE: github.com/StyraInc/opa

jobs:
  update-docs:
    name: Update Docs
    runs-on: ubuntu-22.04
    steps:
      - name: Tune GitHub-hosted runner network
        uses: smorimoto/tune-github-hosted-runner-network@v1
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.PLATFORM_AUTOMATION_GH_APP_ID }}
          private_key: ${{ secrets.PLATFORM_AUTOMATION_GH_APP_PEM_KEY }}
      - name: Override GH Token Env Var
        run: echo "GH_API_TOKEN=${{ steps.generate_token.outputs.token }}" >> $GITHUB_ENV
      - name: Setup github api token
        run: git config --global url.https://git:$GH_API_TOKEN@github.com/.insteadOf https://github.com/
      - uses: actions/checkout@v4
      - id: go_version
        name: Read go version
        run: echo "go_version=$(cat .go-version)" >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go_version.outputs.go_version }}
      - name: Generate CLI Docs
        run: |
          make generate-cli-docs
      - name: Update docs repo
        uses: leigholiver/commit-with-deploy-key@64d2c8705aa10aa475e971b877a7fe6ada69a1a2
        with:
          source: tmp-docs
          destination_folder: imported/artifacts/enterprise-opa-private
          destination_repo: StyraInc/docs
          deploy_key: ${{ secrets.STYRA_DOCS_DEPLOY_KEY }}
